# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :jerome do
    ENV["GIT_MERGE_AUTOEDIT"] = "no"
    sh("git", "flow", "release", "finish", "-F", "-p", "-m", "\"1.0.5\"", "1.0.5")
    ENV["GIT_MERGE_AUTOEDIT"] = nil
  end
end
